version: "3"

services:
  postgres:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: crabi
      POSTGRES_PASSWORD: gateur
      POSTGRES_DB: crabigateur
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5555:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/structure.sql:/docker-entrypoint-initdb.d/structure.sql
